server:
  port: ${APP_PORT:8080}

app:
  base-url: ${APP_BASE_URL:http://localhost:8080}

spring:
  application:
    name: modam

  datasource:
    url: ${DB_URL}
    driver-class-name: oracle.jdbc.OracleDriver
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false


  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    cache: false



  security:
    user:
      name: ${SECURITY_USER_NAME:test}
      password: ${SECURITY_USER_PASSWORD:1234}

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true

logging:
  file:
    name: logs/modam.log
  level:
    root: INFO
    "[com.intelliJ_JO.modam]": DEBUG
    "[org.springframework.security.web.authentication.rememberme]": TRACE
    "[org.springframework.security.web.context]": DEBUG
    "[org.springframework.security.web]": DEBUG

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    url: /v3/api-docs
