server:
  port: 8080

app:
  base-url: http://localhost:8080

spring:
  application:
    name: modam

  datasource:
    url: jdbc:h2:file:./data/modamdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;AUTO_RECONNECT=TRUE
    driver-class-name: org.h2.Driver
    username: test
    password: 1234

  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    cache: false

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: false
    database-platform: org.hibernate.dialect.H2Dialect

  h2:
    console:
      enabled: true
      path: /h2-console

  security:
    user:
      name: test
      password: 1234

  mail:
    host: smtp.gmail.com
    port: 587
    username: kbh02180@gmail.com   # Gmail 주소로 교체
    password: pjgj apso hthq trvi              # Gmail 앱 비밀번호로 교체
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true

logging:
  file:
    name: logs/modam.log
  level:
    root: INFO
    "[com.intelliJ_JO.modam]": DEBUG
    "[org.springframework.security.web.authentication.rememberme]": TRACE
    "[org.springframework.security.web.context]": DEBUG
    "[org.springframework.security.web]": DEBUG

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    url: /v3/api-docs